-- Capa RAW: esquema "schema-on-read". Todo llega como texto tal cual la fuente
-- lo entregó (más columnas de linaje); los tipos se aplican en staging (dbt).
-- Así una fuente que cambia un formato no rompe la carga, rompe un test de dbt.
CREATE TABLE IF NOT EXISTS RAW.API_PARTIDOS (
    MATCH_ID VARCHAR, COMPETICION VARCHAR, TEMPORADA_INICIO VARCHAR, JORNADA VARCHAR,
    FECHA_UTC VARCHAR, ESTADO VARCHAR, LOCAL_ID VARCHAR, LOCAL_NOMBRE VARCHAR,
    VISITANTE_ID VARCHAR, VISITANTE_NOMBRE VARCHAR, GOLES_LOCAL VARCHAR, GOLES_VISITANTE VARCHAR,
    GANADOR VARCHAR, ULTIMA_ACTUALIZACION VARCHAR, EXTRAIDO_EN VARCHAR,
    _LOTE_ID VARCHAR, _CARGADO_EN VARCHAR
);

CREATE TABLE IF NOT EXISTS RAW.GPS_CARGA_FISICA (
    FECHA VARCHAR, JUGADOR_ID VARCHAR, TIPO_SESION VARCHAR, MINUTOS VARCHAR,
    DISTANCIA_TOTAL_M VARCHAR, DISTANCIA_ALTA_INTENSIDAD_M VARCHAR, SPRINTS VARCHAR,
    VELOCIDAD_MAX_KMH VARCHAR, FC_MEDIA_LPM VARCHAR, RPE VARCHAR, ARCHIVO_ORIGEN VARCHAR,
    _LOTE_ID VARCHAR, _CARGADO_EN VARCHAR
);

CREATE TABLE IF NOT EXISTS RAW.TAQUILLA_VENTAS (
    VENTA_ID VARCHAR, FECHA_PARTIDO VARCHAR, CODIGO_COMPETICION VARCHAR, TRIBUNA VARCHAR,
    CANAL VARCHAR, CANTIDAD VARCHAR, PRECIO_UNITARIO VARCHAR, ESTADO VARCHAR,
    CREATED_AT VARCHAR, UPDATED_AT VARCHAR,
    _LOTE_ID VARCHAR, _CARGADO_EN VARCHAR
);
