-- =====================================================================
-- DeporData · Preparación de Snowflake (ejecutar UNA vez con ACCOUNTADMIN
-- o SYSADMIN + SECURITYADMIN desde un worksheet de Snowsight).
--
-- Principio de mínimo privilegio: el pipeline usa un usuario y un rol propios
-- que solo pueden leer/escribir en DEPORTE_DB y usar DEPORTE_WH.
-- Reemplaza <CLAVE_SEGURA> antes de ejecutar (NO la guardes en el repositorio).
-- =====================================================================

USE ROLE SYSADMIN;

-- Warehouse pequeño que se apaga solo al minuto sin uso: el pipeline corre
-- una vez al día, así que pagar por un warehouse encendido no tiene sentido.
CREATE WAREHOUSE IF NOT EXISTS DEPORTE_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse del pipeline DeporData (Airflow + dbt)';

CREATE DATABASE IF NOT EXISTS DEPORTE_DB COMMENT = 'Club Deportivo SQ - datos deportivos y comerciales';

CREATE SCHEMA IF NOT EXISTS DEPORTE_DB.RAW          COMMENT = 'Datos crudos cargados por Airflow (todo VARCHAR + linaje)';
CREATE SCHEMA IF NOT EXISTS DEPORTE_DB.SEEDS        COMMENT = 'Catálogos maestros versionados en dbt (seeds)';
CREATE SCHEMA IF NOT EXISTS DEPORTE_DB.STAGING      COMMENT = 'dbt: limpieza, tipos y deduplicación';
CREATE SCHEMA IF NOT EXISTS DEPORTE_DB.INTERMEDIATE COMMENT = 'dbt: lógica de negocio reutilizable';
CREATE SCHEMA IF NOT EXISTS DEPORTE_DB.MARTS        COMMENT = 'dbt: tablas finales para consumo';
CREATE SCHEMA IF NOT EXISTS DEPORTE_DB.ANALYTICS    COMMENT = 'Schema por defecto del perfil dbt';

USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS DEPORTE_PIPELINE_ROLE COMMENT = 'Rol del pipeline DeporData (mínimo privilegio)';
CREATE ROLE IF NOT EXISTS DEPORTE_LECTOR_ROLE   COMMENT = 'Solo lectura de MARTS para analistas y dashboards';
GRANT ROLE DEPORTE_PIPELINE_ROLE TO ROLE SYSADMIN;
GRANT ROLE DEPORTE_LECTOR_ROLE   TO ROLE SYSADMIN;

GRANT USAGE ON WAREHOUSE DEPORTE_WH TO ROLE DEPORTE_PIPELINE_ROLE;
GRANT USAGE ON WAREHOUSE DEPORTE_WH TO ROLE DEPORTE_LECTOR_ROLE;
GRANT USAGE ON DATABASE DEPORTE_DB  TO ROLE DEPORTE_PIPELINE_ROLE;
GRANT USAGE ON DATABASE DEPORTE_DB  TO ROLE DEPORTE_LECTOR_ROLE;

-- El pipeline crea y reemplaza tablas/vistas SOLO dentro de sus schemas.
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA DEPORTE_DB.RAW          TO ROLE DEPORTE_PIPELINE_ROLE;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA DEPORTE_DB.SEEDS        TO ROLE DEPORTE_PIPELINE_ROLE;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA DEPORTE_DB.STAGING      TO ROLE DEPORTE_PIPELINE_ROLE;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA DEPORTE_DB.INTERMEDIATE TO ROLE DEPORTE_PIPELINE_ROLE;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA DEPORTE_DB.MARTS        TO ROLE DEPORTE_PIPELINE_ROLE;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA DEPORTE_DB.ANALYTICS    TO ROLE DEPORTE_PIPELINE_ROLE;
-- write_pandas usa un stage temporal y un file format temporal.
GRANT CREATE STAGE, CREATE FILE FORMAT ON SCHEMA DEPORTE_DB.RAW TO ROLE DEPORTE_PIPELINE_ROLE;

-- Los analistas solo leen la capa final.
GRANT USAGE ON SCHEMA DEPORTE_DB.MARTS TO ROLE DEPORTE_LECTOR_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DEPORTE_DB.MARTS TO ROLE DEPORTE_LECTOR_ROLE;

CREATE USER IF NOT EXISTS DEPORTE_PIPELINE_USER
    PASSWORD = '<CLAVE_SEGURA>'
    DEFAULT_ROLE = DEPORTE_PIPELINE_ROLE
    DEFAULT_WAREHOUSE = DEPORTE_WH
    DEFAULT_NAMESPACE = DEPORTE_DB.RAW
    MUST_CHANGE_PASSWORD = FALSE
    COMMENT = 'Usuario de servicio de Airflow/dbt';
GRANT ROLE DEPORTE_PIPELINE_ROLE TO USER DEPORTE_PIPELINE_USER;

-- Control de costos: corta el warehouse si se pasa de 5 créditos al mes.
USE ROLE ACCOUNTADMIN;
CREATE RESOURCE MONITOR IF NOT EXISTS DEPORTE_MONITOR
    WITH CREDIT_QUOTA = 5 FREQUENCY = MONTHLY START_TIMESTAMP = IMMEDIATELY
    TRIGGERS ON 80 PERCENT DO NOTIFY
             ON 100 PERCENT DO SUSPEND;
ALTER WAREHOUSE DEPORTE_WH SET RESOURCE_MONITOR = DEPORTE_MONITOR;
